// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYRmlOzlsJKW-lxyWElq5ImhNNSTP9h-8',
    appId: '1:1008212160946:web:bceee3d40c85b08df934ab',
    messagingSenderId: '1008212160946',
    projectId: 'atiqtodo',
    authDomain: 'atiqtodo.firebaseapp.com',
    storageBucket: 'atiqtodo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP8t8pQZ5ZjuRD6r7nbm2kKLXEBICLvPs',
    appId: '1:1008212160946:android:5934141c5f79a124f934ab',
    messagingSenderId: '1008212160946',
    projectId: 'atiqtodo',
    storageBucket: 'atiqtodo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC5QmVD9GJjBegB7-0G4X-hiUlariXIx8',
    appId: '1:1008212160946:ios:9233bef2916ceae2f934ab',
    messagingSenderId: '1008212160946',
    projectId: 'atiqtodo',
    storageBucket: 'atiqtodo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
